apiVersion: apps/v1
kind: Deployment
metadata:
  name: of-builder
  namespace: openfaas
  labels:
    app: of-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: of-builder
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: of-builder
    spec:
      volumes:
        - name: buildkitd-toml
          configMap:
            defaultMode: 420
            name: buildkitd-toml
        - name: fiberhome-ca
          secret:
            defaultMode: 420
            secretName: fiberhome-ca
        - name: registry-secret
          secret:
            defaultMode: 420
            secretName: registry-secret
        - name: payload-secret
          secret:
            defaultMode: 420
            secretName: payload-secret
      containers:
      - name: of-builder
        image: openfaas/of-builder:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
        env:
          - name: enable_lchown
            value: "true"
          - name: insecure
            value: "false"
          - name: buildkit_url  
            value: "tcp://127.0.0.1:1234"
          - name: "disable_hmac"
            value: "true"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: registry-secret
          readOnly: true
          mountPath: "/root/.docker/"
        - name: payload-secret
          readOnly: true
          mountPath: "/var/openfaas/secrets/"
      - name: of-buildkit
        args: ["--addr", "tcp://0.0.0.0:1234"]
        image: moby/buildkit:v0.7.2
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - name: fiberhome-ca
          readOnly: true
          mountPath: "/usr/local/share/ca-certificates/"
        - name: buildkitd-toml
          readOnly: true
          mountPath: "/etc/buildkit/"
